name: whatsapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  firebase_storage: ^12.4.9
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
